# Generated by Django 4.1.1 on 2022-09-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endereco',
            unique_together={('logradouro', 'numero', 'bairro')},
        ),
    ]
