# Generated by Django 4.1 on 2022-09-05 22:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_aluno_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaaluno',
            name='cpf',
            field=models.ForeignKey(db_column='cpf', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cadastros.aluno'),
        ),
        migrations.AlterField(
            model_name='matriculaaluno',
            name='dt_matricula',
            field=models.DateField(default=datetime.date(2022, 9, 5)),
        ),
    ]
