# Generated by Django 4.1.1 on 2022-09-14 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_endereco_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunodisciplina',
            name='cod_grade',
            field=models.ForeignKey(db_column='id_grade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.grade'),
        ),
        migrations.AlterUniqueTogether(
            name='alunodisciplina',
            unique_together={('cpf', 'cod_grade')},
        ),
        migrations.RemoveField(
            model_name='alunodisciplina',
            name='cod_d',
        ),
    ]
