# Generated by Django 4.1 on 2022-09-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_matriculaaluno_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaaluno',
            name='dt_matricula',
            field=models.DateField(auto_now=True),
        ),
    ]
