# Generated by Django 4.1.1 on 2022-09-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_alunodisciplina_cod_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunodisciplina',
            name='cod_aluno_disciplina',
            field=models.IntegerField(default=2),
        ),
    ]
