# Generated by Django 4.1 on 2022-09-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_matriculaaluno_dt_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='ND', max_length=50, null=True),
        ),
    ]
