# Generated by Django 4.1.1 on 2022-09-14 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alunodisciplina_cod_aluno_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunodisciplina',
            name='cod_aluno_disciplina',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alunodisciplina',
            name='cpf',
            field=models.ForeignKey(db_column='cpf', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.aluno'),
        ),
    ]
