# Generated by Django 4.1.1 on 2022-09-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_alunodisciplina_cod_aluno_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sobrenome_aluno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome_c',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome_dep',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome_disciplina',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='ND', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome_prof',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='sobrenome_prof',
            field=models.CharField(max_length=255),
        ),
    ]
