# Generated by Django 4.1.1 on 2022-09-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_aluno_nome_aluno_alter_aluno_sobrenome_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisito',
            name='cod_requisicao',
            field=models.IntegerField(
                blank=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prerequisito',
            name='cod_requisitante',
            field=models.ForeignKey(db_column='cod_requisitante', on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='cod_requisitado', to='cadastros.disciplina'),
        ),
    ]
