# Generated by Django 4.1.1 on 2022-09-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_prerequisito_cod_requisicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisito',
            name='cod_requisicao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
