# Generated by Django 4.1.1 on 2022-09-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_prerequisito_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
