# Generated by Django 4.1.1 on 2022-09-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_delete_teste'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professor',
            unique_together={('matricula_prof', 'nome_prof', 'sobrenome_prof')},
        ),
    ]
