# Generated by Django 4.1.1 on 2022-09-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_professor_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professor',
            unique_together={('nome_prof', 'sobrenome_prof')},
        ),
    ]
