# Generated by Django 4.1.1 on 2022-09-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_professor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dt_nasc',
            field=models.DateField(null=True),
        ),
    ]
