# Generated by Django 4.1.1 on 2022-09-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_alter_contrato_dt_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='dt_contrato',
            field=models.DateField(default='21/09/2022'),
        ),
    ]
