# Generated by Django 4.1.1 on 2022-09-21 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_alter_contrato_dt_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cod_dep',
            field=models.ForeignKey(db_column='cod_dep', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.departamento'),
        ),
    ]
