# Generated by Django 4.1.1 on 2022-09-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_alter_contrato_cod_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculaaluno',
            name='numero_matricula',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dt_contrato',
            field=models.DateField(default='25/09/2022'),
        ),
        migrations.AlterField(
            model_name='matriculaaluno',
            name='cod_c',
            field=models.ForeignKey(db_column='cod_c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.curso'),
        ),
        migrations.AlterField(
            model_name='matriculaaluno',
            name='cpf',
            field=models.ForeignKey(db_column='cpf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='matriculaaluno',
            unique_together={('numero_matricula', 'cpf', 'cod_c')},
        ),
    ]
