# Generated by Django 4.1.1 on 2022-09-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_alter_matriculaaluno_numero_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaaluno',
            name='numero_matricula',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
