# Generated by Django 4.1.1 on 2022-09-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_alter_matriculaaluno_numero_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculaaluno',
            name='cod_c',
            field=models.ForeignKey(db_column='cod_c', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.curso'),
        ),
        migrations.AlterField(
            model_name='matriculaaluno',
            name='cpf',
            field=models.ForeignKey(db_column='cpf', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.aluno'),
        ),
    ]
