# Generated by Django 4.1.1 on 2022-09-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_alter_matriculaaluno_cod_c_alter_matriculaaluno_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.ForeignKey(db_column='matricula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.matriculaaluno'),
        ),
    ]
