# Generated by Django 4.1.1 on 2022-09-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_aluno_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
    ]
