# Generated by Django 4.1.1 on 2022-09-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_remove_aluno_matricula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matriculaaluno',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='matriculaaluno',
            name='cpf',
            field=models.ForeignKey(db_column='cpf', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.aluno', unique=True),
        ),
    ]
