# Generated by Django 4.1.1 on 2022-10-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_alter_matriculaaluno_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
