# Generated by Django 4.1.1 on 2022-10-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_delete_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='data_contrato',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.departamento'),
        ),
        migrations.AddField(
            model_name='professor',
            name='nContrato',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
