# Generated by Django 4.1.1 on 2022-10-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_professor_data_contrato_professor_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='departamento',
            field=models.ForeignKey(db_column='cod_dep', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.departamento'),
        ),
    ]
