# Generated by Django 4.1.1 on 2022-10-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_alter_professor_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='nContrato',
            new_name='n_contrato',
        ),
    ]
